name: WordPress CI
on:
  push:
    branches:
      - main
      - "*.X"
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [8.1]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@86e1ccdd8ddc47bffc29bf667143f363a4cdfdbc
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - name: Composer install
        run: composer install

      - name: PHP tests
        run: ./vendor/bin/phpunit --process-isolation tests

      - name: Package duo-universal
        run: ./package.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: duo-universal
          path: ./duo-universal.zip
