name: WordPress CI
on:
  push:
    branches:
      - main
      - "*.X"
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [8.1]

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2.37.2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - name: Composer install prod dependencies
        run: composer install --no-dev --no-scripts

        # Package before installing dev dependencies so we don't include them in the production zip
      - name: Package duo-universal
        run: ./package.sh

      - name: Composer install dev dependencies
        run: composer install --no-scripts

      - name: PHP tests
        run: ./vendor/bin/phpunit --process-isolation tests

      - name: Print artifact sha256
        run: echo "SHA256 " && sha256sum ./duo-universal.zip

      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: duo-universal
          path: ./duo-universal.zip
