name: WordPress CI
on:
  push:
    branches:
      - main
      - "*.X"
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [8.1]

    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - name: Setup PHP
        uses: shivammathur/setup-php@86e1ccdd8ddc47bffc29bf667143f363a4cdfdbc
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - name: Composer install prod dependencies
        run: composer install --no-dev

        # Package before installing dev dependencies so we don't include them in the production zip
      - name: Package duo-universal
        run: ./package.sh

      - name: Composer install dev dependencies
        run: composer install

      - name: PHP tests
        run: ./vendor/bin/phpunit --process-isolation tests

      - name: Print artifact sha256
        run: echo "SHA256 " && sha256sum ./duo-universal.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: duo-universal
          path: ./duo-universal.zip
